---
- hosts: minecraft 
  gather_facts: No
  user: minecraft
  sudo: no
  vars:
   - files: files
   - craftbukkit_jar: "{{ files }}/craftbukkit.jar"
   - minecraft_root: "/home/minecraft/craftbukkit/main"
  tasks:
   - name: upload newest .jar file
     copy: src={{ craftbukkit_jar }} dest="{{ minecraft_root }}/craftbukkit.jar" backup=yes
     notify: restart minecraft
  handlers:
   - name: restart minecraft
     shell: service minecraft start
     sudo: no
